# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Mahsa Sheikholeslamian"                                
  description: "Researcher, lecturer and dentist with approximately 10 years of experience."   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Education"
        href: education/index.qmd
      - text: "Professional Position"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "New Post"
        href: New/index.qmd
    
    # your social media handles
    right:
      - icon: google scholar
        href: https://scholar.google.com/citations?user=vUVIvJkAAAAJ&hl=en&authuser=1
      - icon: linkedin
        href: https://www.linkedin.com/in/mahsa-sheikh-0442b545/
      - icon: envelope
        aria-label: email
        href: "mailto:sxs3195@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Mahsa Sheikh </span>


project:
   
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true